[versions]
gearyPaper = "0.33.16"
guiy="0.14.2"

[libraries]
geary-papermc = { module = "com.mineinabyss:geary-papermc", version.ref = "gearyPaper" }
guiy = { module = "com.mineinabyss:guiy-compose", version.ref = "guiy" }

minecraft-plugin-protectionlib = "com.nexomc:protectionlib:1.0.8"
minecraft-plugin-axiompaper = "com.moulberry.axiom:AxiomPaper:5.0.1"
